# Generated by Django 2.0 on 2018-01-05 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180105_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.County')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Hospital')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
    ]
