# Generated by Django 2.0 on 2018-01-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='code',
            field=models.IntegerField(default='001', verbose_name=3),
        ),
    ]
