# Generated by Django 2.0 on 2018-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.IntegerField(default='001'),
        ),
    ]
