# Generated by Django 2.0 on 2018-01-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180105_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.IntegerField(default='1'),
        ),
    ]
