# Generated by Django 2.0 on 2018-01-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180105_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.IntegerField(default='1', unique=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
