# Generated by Django 2.1 on 2018-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180105_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='age',
        ),
        migrations.AddField(
            model_name='donor',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
