# Generated by Django 2.1.1 on 2018-10-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_donor_date_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='image_url',
            field=models.ImageField(null=True, upload_to='static/profiles/%Y/%m/%d'),
        ),
    ]
