# Generated by Django 2.1.2 on 2018-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20181011_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=['/home/reuben/projects/dbk_web/media']),
        ),
    ]
