# Generated by Django 2.1.2 on 2018-10-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20181027_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
