# Generated by Django 2.1.2 on 2018-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20181027_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
