# Generated by Django 2.1.2 on 2018-10-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20181027_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
