# Generated by Django 2.1.2 on 2018-10-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20181027_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='news',
            name='width_field',
        ),
    ]
