# Generated by Django 2.1.2 on 2018-10-30 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='county_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.County'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+254712345678'. Up to 15 digits allowed. ", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
