# Generated by Django 2.1.2 on 2018-11-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_appointment_schedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='choose', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='county_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.County'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'female'), (0, 'Not Set')], default=0, null=True),
        ),
    ]
