# Generated by Django 2.1.2 on 2018-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20181115_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='donor',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_photo'),
        ),
    ]
