# Generated by Django 2.1.2 on 2018-11-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20181122_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Not Set', 'Not Set')], default='Not Set', max_length=20, null=True),
        ),
    ]
