# Generated by Django 2.1.2 on 2018-11-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20181124_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Not Set', max_length=20, null=True),
        ),
    ]
