# Generated by Django 2.1.2 on 2018-11-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_county_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='county_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
