# Generated by Django 2.1.2 on 2018-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_auto_20181126_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
