# Generated by Django 2.1.2 on 2018-12-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20181126_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/profiles'),
        ),
    ]
