# Generated by Django 2.1.2 on 2018-12-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20181213_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='max. of One hundred characters', max_length=100),
        ),
    ]
