# Generated by Django 2.1.2 on 2018-12-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20181216_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
