# Generated by Django 2.1.2 on 2019-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20181224_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_donated',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='donated',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
