# Generated by Django 2.1.2 on 2019-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20190407_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='schedule_date',
            field=models.DateField(null=True),
        ),
    ]
