# Generated by Django 2.1.2 on 2019-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20190409_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='donated',
        ),
        migrations.AddField(
            model_name='appointment',
            name='amount_donated',
            field=models.SmallIntegerField(blank=True, help_text='mls', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='has_donated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='has_appointment',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='has_donated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
