# Generated by Django 2.1.2 on 2019-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20190409_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='county_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
