# Generated by Django 2.1.2 on 2019-04-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20190409_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='has_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
