# Generated by Django 2.1.2 on 2019-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20190409_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='county_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
