# Generated by Django 2.1.2 on 2019-04-25 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20190410_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Donor'),
        ),
    ]
