# Generated by Django 2.1.2 on 2019-04-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20190425_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='username',
        ),
        migrations.AddField(
            model_name='appointment',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.Donor'),
        ),
    ]
