# Generated by Django 2.1.2 on 2019-04-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20190425_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='times_donated',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='amount_donated',
            field=models.SmallIntegerField(blank=True, help_text='mls', null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='times_donated',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='donor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
