# Generated by Django 2.1.2 on 2019-04-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='county_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
