# Generated by Django 2.1.2 on 2019-04-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20190425_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
