# Generated by Django 2.1.2 on 2019-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20190428_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_donated',
            field=models.PositiveSmallIntegerField(blank=True, help_text='in mls', null=True),
        ),
    ]
